---
- name: Ensure the monitoring network exists
  docker_network:
    name: monitoring
    state: present

- name: Ensure config persistance location
  file:
    name: "{{ data_persistance_location }}/influxdb/config"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Ensure data persistance location
  file:
    name: "{{ data_persistance_location }}/influxdb/data"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Start an influxdb container
  docker_container:
    name: influxdb
    image: "influxdb:{{influxdb_version}}"
    restart_policy: always
    volumes:
      - "{{ data_persistance_location }}/influxdb/data:/var/lib/influxdb"
    networks:
      - name: monitoring
    published_ports:
      - "8086:8086"
    env:
      INFLUXDB_DATA_COMPACT_THROUGHPUT: "1m"
      INFLUXDB_DATA_COMPACT_THROUGHPUT_BURST: "10m"
    purge_networks: yes
    recreate: no
    state: started

- name: Create a metrics database
  community.general.influxdb_database:
    hostname: "http://localhost:8086"
    database_name: "metrics"

- name: Create a logs database
  community.general.influxdb_database:
    hostname: "http://localhost:8086"
    database_name: "logs"

- name: Create 3 day retention policy for logs
  community.general.influxdb_retention_policy:
      hostname: "http://localhost:8086"
      database_name: "logs"
      policy_name: log_retention
      default: yes
      duration: 3d
      replication: 1

- name: Create 1 week retention policy for metrics
  community.general.influxdb_retention_policy:
      hostname: "http://localhost:8086"
      database_name: "metrics"
      policy_name: metric_retention
      default: yes
      duration: 1w
      replication: 1