- name: Deploy the application stack to a server
  hosts: all

  vars:
    - ansible_user: admin
    - ansible_python_interpreter: "/usr/bin/python3"

  vars_files:
   - "vars/values.yml"
   - "vars/secrets.yml"

  roles:
    - system
    - traefik
    - grafana
    - influxdb
    - telegraf
  

  

