---
- name: Ensure the monitoring network exists
  docker_network:
    name: monitoring
    state: present

- name: Ensure config persistance location
  file:
    name: "{{ data_persistance_location }}/telegraf/config"
    state: directory
    mode: "u=rwx,g=rwx,o=rwx"

- name: Deploy telegraf.conf
  template:
      dest: "{{ data_persistance_location }}/telegraf/config/telegraf.conf" # required. Location to render the template to on the remote machine.
      src: telegraf.conf.j2 # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.


- name: Start a telegraf container
  docker_container:
    name: telegraf
    image: "telegraf:{{telegraf_version}}"
    restart_policy: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "{{ data_persistance_location }}/telegraf/config:/etc/telegraf"
    networks:
      - name: monitoring
    purge_networks: yes
    recreate: yes
    state: started