- name: Install aptitude using apt
  apt: 
    name: aptitude 
    state: latest 
    update_cache: yes 
    force_apt_get: yes

- name: Add contrib non-free repos
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch main contrib non-free
    state: present

- name: Add updates contrib non-free repos
  apt_repository:
    repo: deb http://deb.debian.org/debian-security/ stretch/updates main contrib non-free
    state: present

- name: Add stretch-updates contrib non-free repos
  apt_repository:
    repo: deb http://deb.debian.org/debian stretch-updates main contrib non-free
    state: present

- name: Set authorized key took from file
  authorized_key:
    user: admin
    state: present
    key: "{{ lookup('file', 'ssh/ansible_key.pub') }}"

- name: Check if swap file exists
  stat:
    path: "{{swap_file}}"
  register: swap_file_check

- name: Create swap file
  command: fallocate -l {{swap_file_size}} {{swap_file}}
  when: not swap_file_check.stat.exists

- name: Change swap file permissions
  file: 
    path: "{{swap_file}}"
    owner: root
    group: root
    mode: "600"

- name: Format swap file
  command: "mkswap {{swap_file}}"
  when: not swap_file_check.stat.exists

- name: Write swap entry in fstab
  mount: 
    name: none
    src: "{{swap_file}}"
    fstype: swap
    opts: sw
    passno: "0"
    dump: "0"
    state: present

- name: Turn on swap
  command: swapon -a
  when: not swap_file_check.stat.exists

- name: Do system update
  apt:
    upgrade: full
    update_cache: yes
    autoclean: yes
    autoremove: yes

- name: Install required system packages
  apt: 
    name: "{{ item }}" 
    state: latest 
    update_cache: yes
  loop: [ 'apt-transport-https', 'ca-certificates', 'curl', 'software-properties-common', 'python3-pip', 'virtualenv', 'python3-setuptools']

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present

- name: Add Docker Repository
  apt_repository:
    repo: deb https://download.docker.com/linux/debian stretch stable
    state: present

- name: Update apt and install docker-ce
  apt: 
    update_cache: yes 
    name: "{{item}}" 
    state: latest
  loop: ['containerd.io', 'docker-ce']

- name: Install Docker Module for Python
  pip:
    name: docker
