---
- name: Add influx GPG apt Key
  apt_key:
    url: https://repos.influxdata.com/influxdb.key
    state: present

- name: Add influx Repository
  apt_repository:
    repo: deb https://repos.influxdata.com/debian stretch stable
    state: present

- name: Update apt and install telegraf
  apt: 
    update_cache: yes 
    name: "{{item}}" 
    state: latest
  loop: ['telegraf']

- name: Deploy 50-telegraf.conf
  template:
      dest: "/etc/rsyslog.d/50-telegraf.conf" # required. Location to render the template to on the remote machine.
      src: 50-telegraf.conf.j2 # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.

- name: Deploy telegraf.conf
  template:
      dest: "/etc/telegraf/telegraf.conf" # required. Location to render the template to on the remote machine.
      src: telegraf.conf.j2 # required. Path of a Jinja2 formatted template on the Ansible controller. This can be a relative or absolute path.

- name: Add telegraf to the docker group
  user:
    name: telegraf
    groups: ["docker"]

- name: Restart Telegraf to pick up the new config
  service:
    name: telegraf
    state: restarted

- name: Restart rsyslog to pick up the new config
  service:
    name: rsyslog
    state: restarted